trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "✅ Step 1: Setup"
      node -v
    displayName: Check Node Version

  - script: |
      echo "⬇️ Step 2: Install Serverless CLI"
      npm install -g serverless
    displayName: Install Serverless

  - script: |
      echo "🧪 Step 3: Deploying Lambda"
      set -e  # Exit immediately if a command fails
      sls deploy --stage dev
    displayName: Deploy Lambda
