- script: |
    if ! command -v sls &>/dev/null; then
      if ! command -v node &>/dev/null; then
        echo "Node.js is not installed. Installing Node.js 18..."
        curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        yum install -y nodejs
      fi
      echo "Installing Serverless Framework..."
      npm install -g serverless@2.72.3
    else
      echo "Serverless framework is already installed. Skipping..."
    fi
  displayName: Install Serverless Framework
####