service: node-serverless-project
frameworkVersion: "3"
# configValidationMode: error # Optional: Enables strict config checking

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: dev # ✅ added this line
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.joinworldtech.com
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: false # ✅ You've already created it manually, so set this to false
    endpointType: regional
    apiType: http
# Error:
# Serverless plugin "serverless-domain-manager" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-domain-manager" to install it.
# npx serverless plugin install -n serverless-domain-manager
