service: node-serverless-project
frameworkVersion: "3"
# configValidationMode: error # Optional: Enables strict config checking

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.joinworldtech.com
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: false # ✅ You've already created it manually, so set this to false
    endpointType: regional
    apiType: http
